# Generated by Django 5.0.4 on 2024-04-29 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_typed', models.DateField(blank=True, null=True)),
                ('out_date', models.DateField(blank=True, null=True, verbose_name='outgoing date')),
                ('out_from', models.CharField(max_length=100, verbose_name='from')),
                ('to', models.CharField(max_length=100, verbose_name='to')),
                ('cc', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('hand', models.BooleanField(default=False, verbose_name='hand delivery')),
                ('r_mail', models.BooleanField(default=False, verbose_name='regular mail')),
                ('fax', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='outgoing/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-out_date'],
            },
        ),
    ]
