# Generated by Django 5.0.4 on 2024-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='fax',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
