# Generated by Django 5.0.4 on 2024-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0004_alter_incoming_action_incoming_date_delete_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
