# Generated by Django 5.0.4 on 2024-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0005_alter_incoming_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
