# Generated by Django 5.0.4 on 2024-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0007_alter_incoming_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoming',
            options={'ordering': ['-received', 'subject']},
        ),
        migrations.AlterField(
            model_name='incoming',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
