# Generated by Django 5.0.4 on 2024-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0008_alter_incoming_options_alter_incoming_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='date',
        ),
        migrations.AlterField(
            model_name='incoming',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
