# Generated by Django 5.0.4 on 2024-04-30 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0010_alter_incoming_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
